---
- name: Установка pip и docker модуля
  hosts: webservers
  become: yes
  vars:
    pip_install_packages:
      - name: docker

    # Переменные для роли geerlingguy.docker
    docker_apt_source_signed_by: "/etc/apt/keyrings/docker.asc"
    docker_edition: ce
    docker_install_compose: true

  pre_tasks:
    - name: Удаление старого файла репозитория Docker
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Удаление старого ключа Docker
      ansible.builtin.file:
        path: /usr/share/keyrings/docker-archive-keyring.gpg
        state: absent

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker